language: python
script: python manage.py migrate
before-install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install black
script:
  - black .
  - black --check . 
  - flake8 --max-line-length=130 --ignore=F405,F403,F541,W503,E231,E722
  - cd food_redistribution
  - coverage run -a --source="." manage.py test accounts
  - coverage run -a --source="." manage.py test cal
  - coverage run -a --source="." manage.py test yelp_search.tests.test_views
  - coverage run -a --source="." manage.py test food_avail

after_success:
  - coveralls